"use client";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";
import NavBar from "./navbar";

const inter = Inter({ subsets: ["latin"] });
const disableNavbar = ["/login", "/register"];

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-400`}>
        {!disableNavbar.includes(pathname) && <NavBar></NavBar>}
        {children}
      </body>
    </html>
  );
}
